### ISSUE TITLE
How to handle error from observable after life cycle expires

### ISSUE THREAD

**Issue by arberg** [uber/AutoDispose#164]
**Library version**: 0.5.1

I asked a question here, because I suspect it is not a bug but a consequence of how the library works. 

https://stackoverflow.com/questions/48564771/autodispose-how-to-handle-error-from-observable-after-life-cycle-expires

I am reaching out to you here so you notice my question, while keeping the information available for other users on stackoverflow. 

Here's the full code to make it easier to run it if needed:
https://gist.github.com/arberg/f937aef2b1abc07c7556d86ea0645efd

**Comment by hzsweers** [comment]
When you say `I get an exception which crashes the app from RxJava`, could you add the stacktrace?

**Comment by arberg** [comment]
Yeah, sorry for not including upfront.

The cause exception is the one I throw within the background thread / within the producer.

Fatal Exception: io.reactivex.exceptions.UndeliverableException: java.io.IOException: With AutoDispose 16:56
       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
       at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onError(ObservableCreate.java:74)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:43)
       at io.reactivex.Observable.subscribe(Observable.java:10981)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Caused by java.io.IOException: With AutoDispose 16:56
       at dk.bnr.androidbooking.TestRxJavaLifeCycleErrorAfterStopActivity.lambda$createObservable$1$TestRxJavaLifeCycleErrorAfterStopActivity(TestRxJavaLifeCycleErrorAfterStopActivity.java:46)
       at dk.bnr.androidbooking.TestRxJavaLifeCycleErrorAfterStopActivity$$Lambda$1.subscribe(Unknown Source)
       at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
       at io.reactivex.Observable.subscribe(Observable.java:10981)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by arberg** [comment]
I think I forgot to mention explicitly that if I exclude the AutoDispose life cycle line below, then the error-consumer handles the error (as expected).
`
.to(AutoDispose.with(AndroidLifecycleScopeProvider.from(activity, Lifecycle.Event.ON_STOP)).forObservable())`


 I also tried using AutoDisposePlugins.setOutsideLifecycleHandler, though I think that is for something else.

`AutoDisposePlugins.setOutsideLifecycleHandler(t -> Log.w(TAG, "Ignored exception from OutsideLifecycleHandler: " + t));`

**Comment by hzsweers** [comment]
I don't see anything in that stacktrace from AutoDispose, it seems like it's not actually hitting AutoDispose code?

`setOutsideLifecycleHandler` is for `OutsideLifecycleException`.

**Comment by arberg** [comment]
No of cause its not AutoDispose code that throws the exception. AutoDispose does something that effectively unregisters the errorHandler. It may very well be working as intended hence the question on stackoverflow rather than just a 'bugreport'. It is obviously not an error in RxJava that it propagates an exception if there is no error-handler.

Let me try to rephrase the question. (Actually I forgot to clearly state my question in the text)

Is it possible to use a life cycle provider (AutoDispose), and yet still handle the exception thrown by a producer, thus avoiding it being propagated by RxJava to the main thread and killing the app?

**Comment by hzsweers** [comment]
> AutoDispose does something that effectively unregisters the errorHandler

AutoDispose doesn't do anything with error handling. It's solely pass through and disposal. It passes them all directly to RxJava directly, and actually just reads from RxJava's observer. If you can give me a repo link with a sample that I can build and run, that would be more helpful

**Comment by arberg** [comment]
Interesting. I have attached an android project with a mainActivity with the crashing code. Start the app, an back out of it. Then it crashes.

[AutoDisposeTestErrorHandling.zip](https://github.com/uber/AutoDispose/files/1686843/AutoDisposeTestErrorHandling.zip)

**Comment by hzsweers** [comment]
So I get a crash, but I don't see a stacktrace when I try it. Will investigate more. I also can't recreate this in a unit test 🤔

**Comment by arberg** [comment]
I extracted the crash from Crashlytics, because the LogCat only showed a few lines. I don't know about recreating it in pure java, but it would be interesting as it would clarify the issue I think. Is the unit test pure java, not an androidTest? The threading is important in the issue, that the producer runs on another thread.

**Comment by hzsweers** [comment]
Yeah my test was pure java

**Comment by hzsweers** [comment]
@arberg any update in repro-ing in a unit test?

**Comment by hzsweers** [comment]
Going to close this for now. Please re-open if you can give more details

**Comment by arberg** [comment]
Hi Zac, 

I've gone down another path. Sounds sensible to close issue for now. Thx for the effort.

Best Alex

**Comment by rohandhruva** [comment]
I'm having the same problem was @arberg is having. As they said, I don't think the library is wrong: the same crash can be easily reproduced by calling `onError()` on any subscription that has been disposed (with or without autodispose). For my app, I'm going to use `tryOnError()` instead of `onError()` as workaround. 

@hzsweers , it might be useful to call out this caveat in the README so that people are aware of it.

**Comment by hzsweers** [comment]
you should be checking `isDisposed()` first in any case before calling `onError()` right?

**Comment by rohandhruva** [comment]
I'm not familiar enough with RxJava to confirm that, though I wonder what libraries do.. which is when this issue might be the most relevant.

**Comment by hzsweers** [comment]
Yeah in general you likely shouldn't be calling `onError` manually unless you're signaling to a (delegate) observer (such as in a custom `ObservableSource`'s `subscribeActual()` method) or are signaling to an emitter in a create() factory.

Example from AutoDispose's internals: https://github.com/uber/AutoDispose/blob/master/autodispose/src/main/java/com/uber/autodispose/AutoDisposingObserverImpl.java#L90

**Comment by rohandhruva** [comment]
Thank you, @hzsweers : that's really useful context to have.
