### ISSUE TITLE
Even though unsubscribes, it still cause SplashActivity memory leaks

### ISSUE THREAD

**Issue by blackberry2016** [uber/AutoDispose#184]
Even though unsubscribes, it still cause SplashActivity memory leaks.

Timber.e("dispose .......") is called too
```
// In SplashViewModel
fun initialize(): Completable {
        return Completable
                .fromAction({
                    SystemClock.sleep(10000)
                })
                .applyNewThread()
                .doOnDispose({
                    Timber.e("dispose .......")
                })
    }

// In SplashActivity
model.initialize().autoDisposable(scope(Lifecycle.Event.ON_DESTROY)).subscribe({
            isInitialized = true
            if (!GuideDialogFragment.isShowing) {
                jumpTo(this, MainActivity::class.java)
            }
        })
```

**version 0.6.1**

**Comment by hzsweers** [comment]
This is not enough information for us to help. Can you please link a sample project that reproduces the issue?

**Comment by blackberry2016** [comment]
@hzsweers https://github.com/blackberry2016/AutoDisposeExample

**Comment by hzsweers** [comment]
I'm unable to reproduce this. Set some breakpoints to watch events coming through but everything seems normal. Any other conditions?

```
I/zygote64: Do partial code cache collection, code=30KB, data=23KB
            After code cache collection, code=30KB, data=23KB
            Increasing code cache capacity to 128KB
Received ON_CREATE
Received ON_START
Received ON_RESUME
Received ON_PAUSE
Received ON_STOP
Received ON_DESTROY
Breakpoint reached at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onDispose(LifecycleEventsObservable.java:106)
E/MainActivity: doOnDispose............
Checking ON_CREATE
Received ON_CREATE
Received ON_START
I/zygote64: Do partial code cache collection, code=38KB, data=48KB
            After code cache collection, code=38KB, data=48KB
            Increasing code cache capacity to 256KB
I/zygote64: Compiler allocated 4MB to compile void android.view.View.<init>(android.content.Context, android.util.AttributeSet, int, int)
Received ON_RESUME
Received ON_PAUSE
Received ON_STOP
Received ON_DESTROY
Breakpoint reached at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onDispose(LifecycleEventsObservable.java:106)
E/MainActivity: doOnDispose............
Checking ON_CREATE
Received ON_CREATE
Received ON_START
Received ON_RESUME
Received ON_PAUSE
Received ON_STOP
Received ON_DESTROY
Breakpoint reached at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onDispose(LifecycleEventsObservable.java:106)
E/MainActivity: doOnDispose............
Checking ON_CREATE
Received ON_CREATE
Received ON_START
Received ON_RESUME
I/zygote64: Do full code cache collection, code=110KB, data=94KB
            After code cache collection, code=109KB, data=79KB
Received ON_PAUSE
Received ON_STOP
Received ON_DESTROY
Breakpoint reached at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onDispose(LifecycleEventsObservable.java:106)
E/MainActivity: doOnDispose............
Checking ON_CREATE
Received ON_CREATE
Received ON_START
Received ON_RESUME
Received ON_PAUSE
Received ON_STOP
Received ON_START
Received ON_RESUME
Received ON_PAUSE
I/zygote64: Do partial code cache collection, code=110KB, data=96KB
I/zygote64: After code cache collection, code=110KB, data=96KB
            Increasing code cache capacity to 512KB
            Compiler allocated 6MB to compile void android.view.ViewRootImpl.performTraversals()
Received ON_STOP
Received ON_DESTROY
Breakpoint reached at com.uber.autodispose.android.lifecycle.LifecycleEventsObservable$ArchLifecycleObserver.onDispose(LifecycleEventsObservable.java:106)
E/MainActivity: doOnDispose............
```

**Comment by blackberry2016** [comment]
@hzsweers  I just open the app and press back button quickly for several times

**Comment by hzsweers** [comment]
Right, that's what I was doing to produce those console logs :/. If you can repro, can you see if the destroy event is firing?

**Comment by blackberry2016** [comment]
@hzsweers Have you open the storage permisson for this app?

**Comment by hzsweers** [comment]
Yes

**Comment by blackberry2016** [comment]
i found it happens occasionally and the destroy event is firing everytime. 
```
03-20 09:13:29.033 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
03-20 09:13:29.034 2892-2892/com.nano.android.autodisposeexample E/MainActivity: onDestroy..............
03-20 09:13:30.765 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
03-20 09:13:30.766 2892-2892/com.nano.android.autodisposeexample E/MainActivity: onDestroy..............
03-20 09:13:31.629 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
03-20 09:13:31.630 2892-2892/com.nano.android.autodisposeexample E/MainActivity: onDestroy..............
03-20 09:13:32.479 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
    onDestroy..............
03-20 09:13:33.266 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
03-20 09:13:33.267 2892-2892/com.nano.android.autodisposeexample E/MainActivity: onDestroy..............
03-20 09:13:34.053 2892-2892/com.nano.android.autodisposeexample E/MainActivity: doOnDispose............
03-20 09:13:34.054 2892-2892/com.nano.android.autodisposeexample E/MainActivity: onDestroy..............
```
Shotscreen

https://github.com/blackberry2016/AutoDisposeExample/blob/master/device-2018-03-20-090658.png

https://github.com/blackberry2016/AutoDisposeExample/blob/master/device-2018-03-20-091016.png

**Comment by hzsweers** [comment]
I believe you, but without being able to repro myself it's hard to debug :/

**Comment by charlesdurham** [comment]
I haven't seen a case where the disposable isn't disposed but I do see the leak canary. Pretty sure it's working as intended.

`{ SystemClock.sleep(10000) }` action is scheduled onto some thread. The `Action` captures the enclosing `Activity`. 

Disposable gets disposed on destroy, executor gets shut down and interrupts thread. `SystemClock.sleep` is designed to continue on interruption and re-interrupt when it's done sleeping. This keeps the action and activity around.

I see the same thing with:

```
class MainActivity : AppCompatActivity() {

    var disposable: Disposable? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        disposable = Completable.fromAction { SystemClock.sleep(10000) }
                .subscribeOn(Schedulers.newThread())
                .subscribe()
    }

    override fun onDestroy() {
        super.onDestroy()
        disposable!!.dispose()
    }
}
```

**Comment by hzsweers** [comment]
iiiiiinteresting, did not know that about `SystemClock`! @blackberry2016 does that solve things for you?

**Comment by blackberry2016** [comment]
@hzsweers yep, it was caused by SystemClock. Close this issue now please
