### ISSUE TITLE
Proguard issue

### ISSUE THREAD

**Issue by tasomaniac** [uber/AutoDispose#267]
**Library version**: 1.0.0

**Repro steps or stacktrace**: 
- Checkout the following [commit](https://github.com/tasomaniac/DevWidget/commit/bcd88f2c40851e4a36812e0d5fe7462b8a86c44e) from my project. 
- Install the release version via `./gradlew installFlossRelease`
- Open the app and add a widget to homescreen on ">= Oreo" device. Click `Refresh` icon in the widget and app will crash. 

Here is the Stacktrace:

```
Fatal Exception: java.lang.AbstractMethodError: abstract method "java.lang.Object com.uber.autodispose.lifecycle.a.a(java.lang.Object)"
       at com.uber.autodispose.lifecycle.LifecycleScopes.resolveScopeFromLifecycle$28a56d8f(LifecycleScopes.java:87)
       at com.uber.autodispose.lifecycle.LifecycleScopes.resolveScopeFromLifecycle(LifecycleScopes.java:57)
       at com.uber.autodispose.android.lifecycle.AndroidLifecycleScopeProvider.requestScope(AndroidLifecycleScopeProvider.java:147)
       at com.uber.autodispose.AutoDispose.lambda$autoDisposable$0(AutoDispose.java:83)
       at com.uber.autodispose.AutoDispose.lambda$MhJlo8Z2Vdj4-KIAZlAls6e5pmM(Unknown Source)
       at com.uber.autodispose.-$$Lambda$c$MhJlo8Z2Vdj4-KIAZlAls6e5pmM.call(Unknown Source:2)
       at io.reactivex.internal.operators.completable.CompletableDefer.subscribeActual(CompletableDefer.java:36)
       at io.reactivex.Completable.subscribe(Completable.java:2185)
       at com.uber.autodispose.AutoDisposingCompletableObserverImpl.onSubscribe(AutoDisposingCompletableObserverImpl.java:58)
       at io.reactivex.internal.operators.completable.CompletableObserveOn$ObserveOnCompletableObserver.onSubscribe(CompletableObserveOn.java:67)
       at io.reactivex.internal.operators.completable.CompletableSubscribeOn.subscribeActual(CompletableSubscribeOn.java:36)
       at io.reactivex.Completable.subscribe(Completable.java:2185)
       at io.reactivex.internal.operators.completable.CompletableObserveOn.subscribeActual(CompletableObserveOn.java:34)
       at io.reactivex.Completable.subscribe(Completable.java:2185)
       at com.uber.autodispose.AutoDisposeCompletable.subscribeActual(AutoDisposeCompletable.java:34)
       at io.reactivex.Completable.subscribe(Completable.java:2185)
       at io.reactivex.Completable.subscribe(Completable.java:2284)
       at com.uber.autodispose.AutoDispose$1$1.subscribe(AutoDispose.java:125)
       at com.tasomaniac.devwidget.widget.click.WidgetRefreshActivity.onCreate(WidgetRefreshActivity.kt:31)
       at android.app.Activity.performCreate(Activity.java:7041)
       at android.app.Activity.performCreate(Activity.java:7032)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
       at android.app.ActivityThread.-wrap11(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6753)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

I have optimizations enabled and that causes the problem. It might be a bug in Proguard actually. I've fixed it with the following rule:

```
-keepnames public interface com.uber.autodispose.lifecycle.CorrespondingEventsFunction { *; }
```

I was wondering if this is an ok rule for the library. If there are others having the same issue, it could be added into the repo.

**Comment by hzsweers** [comment]
Yeah I'm not sure, the library is completely proguard friendly as far as I know aside from one rule we package in the arch components package. It's possibly that something goes haywire during D8 running over that lambda?

**Comment by hzsweers** [comment]
Closing for now with that workaround in mind

**Comment by gm4s** [comment]
I have the same issue since I migrated to 1.0.0

We are using this proguard -> https://android.googlesource.com/platform/sdk/+/master/files/proguard-android.txt

**Comment by tasomaniac** [comment]
Just adding a custom rule for the class should be fine. 

After reaching to proguard team, this crash was confirmed as a bug in proguard. I don't think it is fixed yet tho.

**Comment by hzsweers** [comment]
@tasomaniac do you happen to have a link to the issue in proguard?

**Comment by tasomaniac** [comment]
Sure, I was not sure when I was replying but I found it. Here it is https://sourceforge.net/p/proguard/bugs/729/

**Comment by hzsweers** [comment]
Thanks!
