### ISSUE TITLE
Investigate weird test failure in ViewScopeProviderTest

### ISSUE THREAD

**Issue by hzsweers** [uber/AutoDispose#67]
Ignored in #57 

All we get is `Instrumentation run failed due to 'Process crashed.'`. It crashes some time after `onError` is forward to the delegate, but I can't get the debugger to work to properly investigate.

CC @tonycosentini

**Comment by hzsweers** [comment]
Looking back at messages, @tonycosentini actually gets a different, much more helpful error

```
Process: com.uber.autodispose.android.test, PID: 12426
                                                   io.reactivex.exceptions.ProtocolViolationException: Disposable already set!
                                                       at io.reactivex.internal.disposables.DisposableHelper.reportDisposableSet(DisposableHelper.java:157)
                                                       at io.reactivex.internal.disposables.DisposableHelper.validate(DisposableHelper.java:147)
                                                       at io.reactivex.internal.operators.maybe.MaybeDoOnEvent$DoOnEventMaybeObserver.onSubscribe(MaybeDoOnEvent.java:67)
                                                       at io.reactivex.internal.operators.observable.ObservableElementAtMaybe$ElementAtObserver.onSubscribe(ObservableElementAtMaybe.java:58)
                                                       at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
                                                       at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
                                                       at io.reactivex.internal.observers.BasicFuseableObserver.onSubscribe(BasicFuseableObserver.java:66)
                                                       at io.reactivex.internal.operators.observable.ObservableSkip$SkipObserver.onSubscribe(ObservableSkip.java:45)
                                                       at com.uber.autodispose.android.ViewAttachEventsObservable.subscribeActual(ViewAttachEventsObservable.java:48)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at io.reactivex.internal.operators.observable.ObservableSkip.subscribeActual(ObservableSkip.java:28)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at io.reactivex.internal.operators.observable.ObservableElementAtMaybe.subscribeActual(ObservableElementAtMaybe.java:31)
                                                       at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                       at io.reactivex.internal.operators.maybe.MaybeDefer.subscribeActual(MaybeDefer.java:48)
                                                       at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                       at io.reactivex.internal.operators.maybe.MaybeDoOnEvent.subscribeActual(MaybeDoOnEvent.java:39)
                                                       at io.reactivex.Maybe.subscribe(Maybe.java:3725)
                                                       at io.reactivex.Maybe.subscribeWith(Maybe.java:3791)
                                                       at io.reactivex.Maybe.subscribe(Maybe.java:3712)
                                                       at io.reactivex.Maybe.subscribe(Maybe.java:3678)
                                                       at com.uber.autodispose.AutoDisposingObserverImpl.onSubscribe(AutoDisposingObserverImpl.java:47)
                                                       at io.reactivex.subjects.PublishSubject.subscribeActual(PublishSubject.java:85)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at com.uber.autodispose.ObservableScoper$AutoDisposeObservable.subscribeActual(ObservableScoper.java:111)
                                                       at io.reactivex.Observable.subscribe(Observable.java:10842)
                                                       at com.uber.autodispose.ObservableScoper$1.subscribe(ObservableScoper.java:92)
                                                       at com.uber.autodispose.android.ViewScopeProviderTest.observable_offMainThread_shouldFail(ViewScopeProviderTest.java:100)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                       at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                       at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                       at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
                                                       at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
                                                       at android.support.test.internal.statement.UiThreadStatement.evaluate(UiThreadStatement.java:55)
                                                       at android.support.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:270)
                                                       at org.junit.rules.RunRules.evaluate(RunRules.java:20)
                                                       at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                       at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJ
```
